update diagrams based on teacher feedback
AY2425S1-CS2113-T11-1/tp pull request #124
Opened 2024-11-06 11:46 UTC by kennethszj

1. change class diagram to use + and -
2. add colon for entities in sequence diagram

2024-11-06 12:26 UTC, NCF3535 requested changes
Overall the edits do address concerns in #112 but did not follow what was agreed on.

2024-11-06 12:26 UTC, NCF3535 commented on docs/images/TagPatientClassDiagram.png
Should the new class diagram still have the square and circles as compared to the lecture notes? Could try using `!include style.puml`

2024-11-06 12:26 UTC, NCF3535 commented on docs/images/TagPatientClassDiagram.png
Shouldn't the color of the classes follow the rest in being colored according to the architecture diagrams?

2024-11-06 12:26 UTC, NCF3535 commented on docs/diagrams/CompletionRateSequenceDiagram.puml
> +actor ":User" as user
Should add the color codes for the sequence diagrams based on the ones in style.puml for standardisation

2024-11-06 12:26 UTC, NCF3535 commented on docs/images/CompletionRateSequenceDiagram.png
Shouldn't the color of the classes follow be colored according to the architecture diagrams?

2024-11-06 13:42 UTC, kennethszj commented on docs/images/TagPatientClassDiagram.png
have change it to use style puml

2024-11-06 14:46 UTC, NCF3535 reviewed
Just minor fixes more and all should be good!

2024-11-06 14:46 UTC, NCF3535 commented on docs/images/StateSwitchingSequenceDiagram.png
Shouldn't return statements be dotted lines as per #112?

2024-11-06 14:46 UTC, NCF3535 commented on docs/images/TagPatientClassDiagram.png
Should there be an arrow between `Command` and `AddPatientCommand`?

2024-11-07 03:09 UTC, NCF3535 approved these changes
LGTM, good job on the changes

2024-11-07 03:18 UTC, merged